---
title: "Transformation"
author:
- Garben Logghe
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
---

# Setup 

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = TRUE)
```

Load libraries:

```{r message = FALSE}
library(dplyr)          # To do data science
library(tidylog)        # To provide feedback on dplyr functions
library(here)           # To find files
library(readxl)         # To read Excel files
library(readr)          # To write csv
```

## Read source data

```{r}
dataVlinders <- read_xlsx(here::here("data", "raw", "Dagvlinders.xlsx"))
```

## Construct taxonomy file

```{r}
taxa <- dataVlinders %>% 
	select(Species,
	       Kingdom,
	       Order,
				 Suborder,
				 Family) %>% 
	distinct %>%
	rename(speciesID = Species,
				 suborder = Suborder) %>% 
	mutate(species = str_replace(speciesID, "_", " "))
taxa

taxa <- gbif_species_name_match(df = taxa,
																name = "species")
```

## Write data

```{r}
write_csv(data, here::here("data", "processed", "taxa.csv"), na = "")
```

